func main()
	try
		raise(new Exception("test"))
	except Exception as e
		print(str(e))

