class MyError extends Exception

void test(Exception *_e)
	try
		raise(_e)
	except MyError as e
		print("MyError " + str(e))
#	except Exception as e
#		print("Exception " + str(e))

void main()
	try
		test(new MyError("aaa"))
		test(new Exception("bbb"))
	except Exception as e
		print("end: " + str(e))
